### ISSUE TITLE
Error when training on GPU: AttributeError: 'torch.dtype' object has no attribute 'type'

### ISSUE THREAD

**Issue by rachmadvwp** [Hananel-Hazan/bindsnet#232] opened 2019-04-23 11:44 UTC
Hi,
I'd like to ask.
I was trying to train the network for mnist in GPU. However, I got this error.

> Progress: 0 / 60000 (0.0000 seconds)
> ...
> Progress: 250 / 60000 (4.8947 seconds)
> Traceback (most recent call last):
>   File "eth_mnist.py", line 141, in <module>
>     % (accuracy['all'][-1], np.mean(accuracy['all']), np.max(accuracy['all'])))
>   File "/anaconda3/envs/BindsNET/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3118, in mean
>     out=out, **kwargs)
>   File "/anaconda3/envs/BindsNET/lib/python3.7/site-packages/numpy/core/_methods.py", line 85, in _mean
>     ret = ret.dtype.type(ret / rcount)
> AttributeError: 'torch.dtype' object has no attribute 'type'

Do you know how to fix this?
Thanks

**Comment by djsaunde** [comment] 2019-04-23 12:01
I'm not able to reproduce this error on my machine. Could you send me the output of `pip list` on your machine?

**Comment by rachmadvwp** [comment] 2019-04-23 12:05
Here is the pip list
fyi: i'm a beginner on using GPU 
 
> $ pip list
> Package         Version     Location                 
> --------------- ----------- -------------------------
> atomicwrites    1.3.0       
> attrs           19.1.0      
> bindsnet        0.2.3       
> certifi         2018.11.29  
> chardet         3.0.4       
> cloudpickle     0.8.0       
> cycler          0.10.0      
> Cython          0.29.6      
> dask            1.1.3       
> decorator       4.3.2       
> future          0.17.1      
> gym             0.12.0      
> idna            2.8         
> kiwisolver      1.0.1       
> matplotlib      3.0.3       
> more-itertools  6.0.0       
> networkx        2.2         
> numpy           1.16.2      
> opencv-python   4.0.0.21    
> pandas          0.24.1      
> Pillow          5.4.1       
> pip             19.0.3      
> pluggy          0.9.0       
> py              1.8.0       
> pyglet          1.3.2       
> pyparsing       2.3.1       
> pytest          4.3.0       
> python-dateutil 2.8.0       
> pytz            2018.9      
> PyWavelets      1.0.2       
> requests        2.21.0      
> scikit-image    0.14.2      
> scikit-learn    0.20.3      
> scipy           1.2.1       
> setuptools      40.8.0      
> six             1.12.0      
> toolz           0.9.0       
> torch           1.0.1.post2 
> tqdm            4.31.1      
> urllib3         1.24.1      
> wheel           0.33.1      
> 

Thanks

**Comment by djsaunde** [comment] 2019-04-23 12:16
Did you make any changes to `eth_mnist.py` before running it?

**Comment by djsaunde** [comment] 2019-04-23 12:23
There's a fix for this bug in the `master` branch; clone the repository and do `pip install -e .` in the top-most directory to install it. Or, I'll put together a new PyPI release soon, and you can wait for that. Or, change the print statements on lines 113-116 to:

```accuracy['all'].append(
    100 * torch.sum(labels[i - update_interval:i].long() == all_activity_pred).item() / update_interval
)
accuracy['proportion'].append(
    100 * torch.sum(labels[i - update_interval:i].long() == proportion_pred).item() / update_interval
)

**Comment by rachmadvwp** [comment] 2019-04-23 12:40
It works so far with the modified codes.
Thanks a lot for the help.

**Closed** 2019-04-23 13:37 UTC
